[package]
name = "core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# WASM & Serde Glue
wasm-bindgen         = "0.2.87"
serde                = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen   = "0.6.5"
wasm-bindgen-futures = "0.4.37"

# RaptorQ FEC Engine
raptorq              = { version = "2.0.0", default-features = false, features = ["serde_support"] }

# Logging & Panics
console_error_panic_hook = "0.1.7"
log = "0.4.20"
console_log = { version = "1.0" }

# Async Helpers
futures              = "0.3.28"
getrandom            = { version = "0.2.10", features = ["js"] }